// site/data.jsx — Mock data for Garip Ticaret

const CATEGORIES = [
  { slug: 'mutfak',         name: 'Mutfak',           icon: '🫕' },
  { slug: 'sofra',          name: 'Sofra',             icon: '🍽️' },
  { slug: 'banyo',          name: 'Banyo',             icon: '🛁' },
  { slug: 'dekor',          name: 'Dekor',             icon: '🪴' },
  { slug: 'ceyiz-paketleri',name: 'Çeyiz Paketleri',   icon: '🎁' },
  { slug: 'yeni-gelenler',  name: 'Yeni Gelenler',     icon: '✨' },
];

const PRODUCTS = [
  { id:1,  slug:'seramik-tencere-seti',    name:'Seramik Kaplama Tencere Seti — 5 Parça',  category:'Mutfak',  categorySlug:'mutfak',  price:1500, discountPrice:1125, discountPercent:25, isNew:false, isDiscounted:true,  isFeatured:true,  stock:12, brand:'Garip Home', material:'Seramik Kaplama Alüminyum', color:'Antrasit', volume:'16–32 cm', shortDesc:'Yapışmaz seramik kaplama, PFOA içermez. 5 farklı boyut.', desc:'Yapışmaz seramik kaplama sayesinde yağsız pişirme imkânı sunan bu set PFOA ve PTFE içermez.\n\nAlüminyum gövde ısıyı eşit dağıtarak mükemmel sonuçlar sağlar. Şık ergonomik saplı tasarımıyla her mutfağa uyum sağlar.', image:'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop', images:['https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop','https://images.unsplash.com/photo-1574673620948-26155ea1b4f2?w=600&auto=format&fit=crop','https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=600&auto=format&fit=crop'] },
  { id:2,  slug:'porselen-tabak-seti',     name:'El Boyaması Porselen Tabak Seti — 6\'lı', category:'Sofra',   categorySlug:'sofra',   price:890,  discountPrice:null, discountPercent:0,  isNew:true,  isDiscounted:false, isFeatured:true,  stock:8,  brand:'Ateş Seramik', material:'Porselen', color:'Krem / Mavi', volume:'27 cm', shortDesc:'El boyaması, her biri özgün. Bulaşık makinesine uygun.', desc:'Usta seramikçilerin elinden çıkan bu tabaklar, her birinin kendine özgü desen detayıyla gerçek bir el sanatı eseri.\n\nBulaşık makinesine ve mikrodalgaya uygundur.', image:'https://images.unsplash.com/photo-1616486029423-aaa4789e8c9a?w=600&auto=format&fit=crop', images:['https://images.unsplash.com/photo-1616486029423-aaa4789e8c9a?w=600&auto=format&fit=crop','https://images.unsplash.com/photo-1606214538804-bd9fcc2f46b4?w=600&auto=format&fit=crop'] },
  { id:3,  slug:'bambu-catal-bicak',       name:'Bambu Saplı Çatal Bıçak Takımı — 24\'lü', category:'Sofra',   categorySlug:'sofra',   price:650,  discountPrice:490,  discountPercent:25, isNew:false, isDiscounted:true,  isFeatured:false, stock:20, brand:'Doğa Ev', material:'Paslanmaz Çelik & Bambu', color:'Naturel', volume:'—', shortDesc:'24 parça paslanmaz çelik gövde, bambu sap. 6 kişilik.', desc:'Doğal bambu sapları ve paslanmaz çelik gövdeleriyle hem estetik hem dayanıklı. Bulaşık makinesine uygun.\n\n6 kişilik set; çatal, bıçak, çorba kaşığı ve tatlı kaşığından oluşur.', image:'https://images.unsplash.com/photo-1574673620948-26155ea1b4f2?w=600&auto=format&fit=crop', images:['https://images.unsplash.com/photo-1574673620948-26155ea1b4f2?w=600&auto=format&fit=crop'] },
  { id:4,  slug:'dogal-lif-banyo-seti',    name:'Doğal Lif Banyo Havlu Seti — 6\'lı',      category:'Banyo',   categorySlug:'banyo',   price:420,  discountPrice:null, discountPercent:0,  isNew:true,  isDiscounted:false, isFeatured:true,  stock:15, brand:'Pamuk Ada', material:'%100 Organik Pamuk', color:'Kum Beji', volume:'50×90 cm', shortDesc:'GOTS sertifikalı organik pamuk. Ultra emici dokuma.', desc:'%100 organik Türk pamuğundan üretilmiş bu havlu seti, tüm aile için ideal. GOTS sertifikalı, çevre dostu boyalarla işlenmiş.\n\n2 banyo havlusu, 2 el havlusu ve 2 yüz bezi içerir.', image:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&auto=format&fit=crop', images:['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&auto=format&fit=crop'] },
  { id:5,  slug:'ahsap-cerceveli-ayna',    name:'Ahşap Çerçeveli Yuvarlak Ayna — 60 cm',   category:'Dekor',   categorySlug:'dekor',   price:1200, discountPrice:null, discountPercent:0,  isNew:false, isDiscounted:false, isFeatured:true,  stock:5,  brand:'Ağaç & Form', material:'Masif Meşe', color:'Naturel Ahşap', volume:'60 cm çap', shortDesc:'Masif meşe çerçeve, el işçiliği. Duvara montaj dahil.', desc:'El işçiliğiyle şekillendirilmiş masif meşe çerçeve, her mekâna sıcaklık katar. Duvara montaj aparatı kutuda yer alır.', image:'https://images.unsplash.com/photo-1582582621959-48d27397dc69?w=600&auto=format&fit=crop', images:['https://images.unsplash.com/photo-1582582621959-48d27397dc69?w=600&auto=format&fit=crop'] },
  { id:6,  slug:'kahve-fincan-seti',       name:'Mermer Desenli Kahve Fincan Seti — 6\'lı', category:'Mutfak',  categorySlug:'mutfak',  price:380,  discountPrice:285,  discountPercent:25, isNew:false, isDiscounted:true,  isFeatured:false, stock:18, brand:'Ateş Seramik', material:'Porselen', color:'Beyaz / Gri Mermer', volume:'80 ml', shortDesc:'Mermer desenli porselen, altın detaylı sap. Türk kahvesine özel.', desc:'Türk kahvesinin özgün lezzetine yakışır bir sunum için. 6 fincan ve 6 tabaktan oluşan bu set, her özel anı tamamlar.', image:'https://images.unsplash.com/photo-1606214538804-bd9fcc2f46b4?w=600&auto=format&fit=crop', images:['https://images.unsplash.com/photo-1606214538804-bd9fcc2f46b4?w=600&auto=format&fit=crop'] },
  { id:7,  slug:'pamuk-masa-ortusu',       name:'El Dokuması Pamuk Masa Örtüsü',           category:'Sofra',   categorySlug:'sofra',   price:550,  discountPrice:null, discountPercent:0,  isNew:true,  isDiscounted:false, isFeatured:false, stock:10, brand:'Dokuma Köy', material:'%100 Doğal Pamuk', color:'Kırık Beyaz / Naturel', volume:'140×240 cm', shortDesc:'Geleneksel Türk dokumacılığı. 6–8 kişilik masa.', desc:'Anadolu dokumacılığının izlerini taşıyan bu masa örtüsü, sofralarınıza otantik ve sıcak bir dokunuş katar.', image:'https://images.unsplash.com/photo-1596484552834-0a373b98402a?w=600&auto=format&fit=crop', images:['https://images.unsplash.com/photo-1596484552834-0a373b98402a?w=600&auto=format&fit=crop'] },
  { id:8,  slug:'cam-kapakli-kavonoz',     name:'Cam Kapaklı Saklama Kavanozu Seti — 5\'li',category:'Mutfak',  categorySlug:'mutfak',  price:340,  discountPrice:null, discountPercent:0,  isNew:false, isDiscounted:false, isFeatured:false, stock:25, brand:'Garip Home', material:'Borosilikat Cam & Bambu', color:'Şeffaf', volume:'0.5L – 2.5L', shortDesc:'Hava geçirmez bambu kapaklı borosilikat cam.', desc:'Buzdolabından fırına geçebilen borosilikat cam gövde. Bambu kapaklar sıkıca kapanır, tazeliği korur. 5 farklı boyutta gelir.', image:'https://images.unsplash.com/photo-1615874959474-d609969a9928?w=600&auto=format&fit=crop', images:['https://images.unsplash.com/photo-1615874959474-d609969a9928?w=600&auto=format&fit=crop'] },
  { id:9,  slug:'banyo-paspas',            name:'El Dokuması Banyo Paspası — 2\'li Set',   category:'Banyo',   categorySlug:'banyo',   price:280,  discountPrice:210,  discountPercent:25, isNew:false, isDiscounted:true,  isFeatured:false, stock:30, brand:'Pamuk Ada', material:'Organik Pamuk Chenille', color:'Kum Beji / Terrakota', volume:'50×80 cm + 40×60 cm', shortDesc:'Kaymaz taban, organik pamuk. Yıkamaya dayanıklı.', desc:'Kaymaz alt yüzeyi ve organik pamuklu üst yüzeyi sayesinde banyonuza hem güvenlik hem estetik katar.', image:'https://images.unsplash.com/photo-1584286595398-a59f21d313f5?w=600&auto=format&fit=crop', images:['https://images.unsplash.com/photo-1584286595398-a59f21d313f5?w=600&auto=format&fit=crop'] },
  { id:10, slug:'aromali-mum',             name:'El Dökümü Aromali Mum Koleksiyonu — 3\'lü',category:'Dekor',   categorySlug:'dekor',   price:320,  discountPrice:null, discountPercent:0,  isNew:true,  isDiscounted:false, isFeatured:false, stock:40, brand:'Işık & Koku', material:'%100 Soya Mumu & Doğal Esans', color:'Krem / Terrakota / Antrasit', volume:'250g / 180 saat', shortDesc:'Uzun ömürlü soya mumu. Bergamot, sandal ağacı, lavanta.', desc:'%100 soya mumundan üretilmiş, doğal esanslarla kokulandırılmış koleksiyon. Her renk farklı esansı temsil eder.', image:'https://images.unsplash.com/photo-1617196035154-1e7e6e28b0db?w=600&auto=format&fit=crop', images:['https://images.unsplash.com/photo-1617196035154-1e7e6e28b0db?w=600&auto=format&fit=crop'] },
  { id:11, slug:'dokme-demir-tava',        name:'Dökme Demir Izgara Tava — 28 cm',         category:'Mutfak',  categorySlug:'mutfak',  price:780,  discountPrice:585,  discountPercent:25, isNew:false, isDiscounted:true,  isFeatured:true,  stock:7,  brand:'Kor Mutfak', material:'Dökme Demir', color:'Mat Siyah', volume:'28 cm', shortDesc:'Ön yüzeylendirilmiş dökme demir. Tüm ocak tiplerine uygun.', desc:'Ömürlük kullanım için tasarlanmış dökme demir tava. Fabrika yüzeylendirilmesiyle kullanıma hazır, zamanla daha iyi performans verir.', image:'https://images.unsplash.com/photo-1590371077726-258dc75d3115?w=600&auto=format&fit=crop', images:['https://images.unsplash.com/photo-1590371077726-258dc75d3115?w=600&auto=format&fit=crop'] },
  { id:12, slug:'porselen-cay-seti',       name:'İnce Porselen Çay Seti — 12\'li',         category:'Sofra',   categorySlug:'sofra',   price:650,  discountPrice:null, discountPercent:0,  isNew:false, isDiscounted:false, isFeatured:false, stock:14, brand:'Ateş Seramik', material:'İnce Porselen', color:'Beyaz / Altın Kenar', volume:'170 ml', shortDesc:'12 çay bardağı + tabak. Altın kaplama detay.', desc:'Geleneksel Türk çay kültürünün vazgeçilmezi, ince belli forma sahip bu set, her sofrayı şenlendirir.', image:'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=600&auto=format&fit=crop', images:['https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=600&auto=format&fit=crop'] },
  { id:13, slug:'ahsap-kasik-seti',        name:'El Yontması Ahşap Mutfak Seti — 6\'lı',   category:'Mutfak',  categorySlug:'mutfak',  price:190,  discountPrice:null, discountPercent:0,  isNew:true,  isDiscounted:false, isFeatured:false, stock:35, brand:'Doğa Ev', material:'Masif Zeytin Ağacı', color:'Naturel', volume:'Çeşitli', shortDesc:'Zeytin ağacından el yontması. Her biri eşsiz desen.', desc:'Ege\'nin bereketli zeytin bahçelerinden gelen ağaçlardan el yontmasıyla üretilen bu set, mutfağınıza doğallık katar.', image:'https://images.unsplash.com/photo-1584286595398-a59f21d313f5?w=600&auto=format&fit=crop', images:['https://images.unsplash.com/photo-1584286595398-a59f21d313f5?w=600&auto=format&fit=crop'] },
  { id:14, slug:'dogal-tas-sabunluk',      name:'Doğal Taş Sabunluk & Aksesuar Seti',      category:'Banyo',   categorySlug:'banyo',   price:145,  discountPrice:null, discountPercent:0,  isNew:false, isDiscounted:false, isFeatured:false, stock:22, brand:'Taş & Toprak', material:'Mermer & Granit', color:'Beyaz Mermer', volume:'—', shortDesc:'Mermer sabunluk, diş fırçalık ve kaplı.', desc:'Doğal mermer ve granit taşlardan üretilmiş banyo aksesuar seti; sabunluk, diş fırçalık ve sabun kapaklı kutudan oluşur.', image:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&auto=format&fit=crop', images:['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&auto=format&fit=crop'] },
  { id:15, slug:'keten-yastik-kilifi',     name:'Naturel Keten Yastık Kılıfı Seti — 4\'lü',category:'Dekor',   categorySlug:'dekor',   price:440,  discountPrice:330,  discountPercent:25, isNew:false, isDiscounted:true,  isFeatured:false, stock:16, brand:'Dokuma Köy', material:'%100 Keten', color:'Naturel / Terrakota / Gri Bej', volume:'50×50 cm', shortDesc:'3 renk seçeneği. Fermuarlı kapama. Yıkama makinesi uyumlu.', desc:'Doğal keten lifinden üretilen yastık kılıfları hem nefes alır hem de zamanla daha yumuşak bir his verir.', image:'https://images.unsplash.com/photo-1582582621959-48d27397dc69?w=600&auto=format&fit=crop', images:['https://images.unsplash.com/photo-1582582621959-48d27397dc69?w=600&auto=format&fit=crop'] },
  { id:16, slug:'bambu-mutfak-rafi',       name:'Bambu Tezgah Üstü Mutfak Rafı',           category:'Mutfak',  categorySlug:'mutfak',  price:520,  discountPrice:null, discountPercent:0,  isNew:false, isDiscounted:false, isFeatured:false, stock:9,  brand:'Doğa Ev', material:'Sürdürülebilir Bambu', color:'Naturel Bambu', volume:'35×20×25 cm', shortDesc:'2 katlı tezgah üstü raf. Baharatlık & malzeme düzeni.', desc:'FSC sertifikalı bambudan üretilmiş bu düzenleyici raf, mutfak tezgâhını her zaman derli toplu tutar.', image:'https://images.unsplash.com/photo-1596484552834-0a373b98402a?w=600&auto=format&fit=crop', images:['https://images.unsplash.com/photo-1596484552834-0a373b98402a?w=600&auto=format&fit=crop'] },
];

const DOWRY_PACKAGES = [
  { id:1, slug:'accord-ceyiz', title:'Accord Çeyiz Paketi', badge:'Peşin Fiyatına 6 Taksit', price:12500, date:'Son Tarih: 30.04.2026', images:['https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=300&auto=format','https://images.unsplash.com/photo-1616486029423-aaa4789e8c9a?w=300&auto=format','https://images.unsplash.com/photo-1574673620948-26155ea1b4f2?w=300&auto=format','https://images.unsplash.com/photo-1606214538804-bd9fcc2f46b4?w=300&auto=format'] },
  { id:2, slug:'elite-ceyiz',  title:'Elite Çeyiz Paketi',  badge:'Peşin Fiyatına 6 Taksit', price:22000, date:'Son Tarih: 30.04.2026', images:['https://images.unsplash.com/photo-1590371077726-258dc75d3115?w=300&auto=format','https://images.unsplash.com/photo-1615874959474-d609969a9928?w=300&auto=format','https://images.unsplash.com/photo-1617196035154-1e7e6e28b0db?w=300&auto=format','https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=300&auto=format'] },
  { id:3, slug:'prestige-ceyiz',title:'Prestige Çeyiz Paketi',badge:'Peşin Fiyatına 6 Taksit',price:38000, date:'Son Tarih: 30.04.2026', images:['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=300&auto=format','https://images.unsplash.com/photo-1582582621959-48d27397dc69?w=300&auto=format','https://images.unsplash.com/photo-1596484552834-0a373b98402a?w=300&auto=format','https://images.unsplash.com/photo-1584286595398-a59f21d313f5?w=300&auto=format'] },
];

function fmt(val) {
  return '₺' + Number(val).toLocaleString('tr-TR', { minimumFractionDigits: 2 });
}

Object.assign(window, { CATEGORIES, PRODUCTS, DOWRY_PACKAGES, fmt });
